env:
  browser: true
  commonjs: true
  es6: true
  screeps/screeps: true
extends: 'eslint:recommended'
plugins:
  - screeps
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
