'use strict';
const states = {
  INITIALISING: 'INITIALISING',
  HARVESTING: 'HARVESTING',
  TRANSFERRING: 'TRANSFERRING',
  UPGRADING: 'UPGRADING',
  BUILDING: 'BUILDING',
};

module.exports = states;
